{
 "title": "Bird detection",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "鳥の検出数 / Bird count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 21, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregation": "none",
     "assetQuery": {
      "includeSubtrees": false,
      "target": ""
     },
     "eventQuery": {
      "activeAtTimeRange": true,
      "columns": [
       "externalId",
       "type",
       "subtype",
       "description",
       "startTime",
       "endTime"
      ],
      "expr": ""
     },
     "tab": "Timeseries",
     "target": "OGA-W11-Detected_No_Bird_Test",
     "targetRefType": "externalId"
    }
   ]
  },
  {
   "title": "信頼度 / Confidence",
   "type": "graph",
   "gridPos": { "h": 6, "w": 21, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregation": "none",
     "assetQuery": {
      "includeSubtrees": false,
      "target": ""
     },
     "eventQuery": {
      "activeAtTimeRange": true,
      "columns": [
       "externalId",
       "type",
       "subtype",
       "description",
       "startTime",
       "endTime"
      ],
      "expr": ""
     },
     "tab": "Timeseries",
     "target": "OGA-W11-Bird_Detection_Confidence_Test",
     "targetRefType": "externalId"
    }
   ]
  },
  {
   "title": "サイズ / Size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 21, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregation": "none",
     "assetQuery": {
      "includeSubtrees": false,
      "target": ""
     },
     "eventQuery": {
      "activeAtTimeRange": true,
      "columns": [
       "externalId",
       "type",
       "subtype",
       "description",
       "startTime",
       "endTime"
      ],
      "expr": ""
     },
     "tab": "Timeseries",
     "target": "OGA-W11-Bird_Detection_Size_Test",
     "targetRefType": "externalId"
    }
   ]
  }
 ]
}